version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./client:/app

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    volumes:
      - ./server:/app
  

